### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by MickeyKay** [verbose/grunt-verb#13]
Just checking in to see what the future plans are for grunt-verb. Based on https://github.com/verbose/grunt-verb/issues/12 it's my understanding that the project is currently in a non-functional state. I've been using grunt-readme in the meantime, however I've now run into another issue there: https://github.com/jonschlinkert/grunt-readme/issues/50

I'd love to switch over to grunt-verb, however it seems like this project hasn't been updated in ages. Can you please confirm what the plans are for this repo? Thanks!

**Comment by jonschlinkert** [comment]
closing since this is an unanswerable question. this is an open source project that relies on contributions from users like you to stay up-to-date. 

Please feel free to create an issue about a specific bug or feature request. Pull requests are also gratefully appreciated.
