### ISSUE TITLE
Example gruntfile?

### ISSUE THREAD

**Issue by bahmutov** [verbose/grunt-verb#2]
After using grunt-readme for a while, I cannot figure out how to use grunt-verb.

**Comment by jonschlinkert** [comment]
Verb doesn't require the same kind of config as grunt-readme, here are the defaults: https://github.com/assemble/grunt-verb/blob/master/tasks/verb.js#L72-L87. 

I do need to add examples, thanks for the reminder.

**Comment by nhubbard** [comment]
I figured it out... you build your documentation to Verb's standards, then add the NPM task and Verb to your default task.

``` javascript
grunt.loadNpmTasks('grunt-verb');
grunt.registerTask('default', ['verb']);
```

**Comment by jonschlinkert** [comment]
thanks@nhubbard. fwiw I'll be updating this plugin in the next couple of days for verb 0.3.0, I'll be sure to add better docs too

**Comment by nhubbard** [comment]
You're welcome, @jonschlinkert!
